jwt_auth:
  domain: '%env(AUTH0_DOMAIN)%'
  authorized_issuer: https://%env(AUTH0_DOMAIN)%/
  api_identifier: '%env(AUTH0_AUDIENCE)%'
#  api_client_id: '%env(AUTH0_CLIENT_ID)%'
#  api_secret: '%env(AUTH0_CLIENT_SECRET)%'
#  api_identifier_array:
#    redirect_uri: '%env(AUTH0_REDIRECT_URI)%'
#    audience: '%env(AUTH0_AUDIENCE)%'
#    scope: 'openid offline_access read:users'
