auth0_callback:
  path:       /callback
  controller: App\Interfaces\Web\Controller\Api\Auth0Controller::callback
  methods:    GET

auth0_login:
  path:       /auth0_login
  controller: App\Interfaces\Web\Controller\Api\Auth0Controller::login
  methods:    GET

auth0_logout:
  path:       /auth0_logout
  controller: App\Interfaces\Web\Controller\Api\Auth0Controller::logout
  methods:    GET

auth0_refreshToken:
  path:       /auth0_refresh_token
  controller: App\Interfaces\Web\Controller\Api\Auth0Controller::refreshToken
  methods:    GET