getUsers:
  path:       /users
  controller: App\Interfaces\Web\Controller\UserController::getUsers
  methods:    GET

createUser:
  path:       /users
  controller: App\Interfaces\Web\Controller\UserController::createUser
  methods:    POST

getUser:
  path:       /users/{id}
  controller: App\Interfaces\Web\Controller\UserController::getUser
  methods:    GET

deleteUser:
  path:       /users{id}
  controller: App\Interfaces\Web\Controller\UserController::deleteUser
  methods:    DELETE