# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Box settings
  config.vm.box = "ubuntu/bionic64"

  #Provider settings
  config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 4
  end

  # Network settings
#   config.vm.network "forwarded_port", guest: 1234, host: 1234
#   config.vm.network "forwarded_port", guest: 1235, host: 1235
  config.vm.network "forwarded_port", guest: 1234, host: 1234, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 1235, host: 1235, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  # Folder settings
  config.vm.synced_folder "../", "/var/www/html",
  :nfs => {
    :mount_options => ["dmode=777", "fmode=666"]
  }

  # Provision settings
  config.vm.provision "shell", path: "bootstrap.sh"
    #   config.vm.provision "shell", path: "dev.sh", run: "always"
end
