login:
  path:       /login
#  controller: App\Interfaces\Web\Controller\SecurityController::login
#  methods:    GET|POST

#logout:
#  path:       /logout
#  methods:    GET

login_check:
  path: /api/login_check
  methods: [POST]

refresh_token:
  path: /api/token/refresh
  controller: App\Interfaces\Web\Controller\SecurityController::refreshToken